# Generated by Django 3.2 on 2021-04-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='name1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='personal_info',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='NOINFO', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(default='NOINFO', max_length=64),
        ),
    ]
