# Generated by Django 3.2 on 2021-04-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210424_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='VSEROS', max_length=64),
        ),
    ]
