# Generated by Django 3.2 on 2021-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
