# Generated by Django 3.2 on 2021-04-24 10:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_event_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name1', models.CharField(default='Untitled', max_length=64)),
                ('name2', models.CharField(default='Untitled', max_length=64)),
                ('name3', models.CharField(default='Untitled', max_length=64)),
                ('organization', models.CharField(default='Untitled', max_length=64)),
                ('position', models.CharField(default='Untitled', max_length=64)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
