# Generated by Django 3.2 on 2021-04-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='diploma',
            field=models.CharField(default='default_file.jpg', max_length=64),
        ),
    ]
