# Generated by Django 3.2 on 2021-04-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='diploma',
            field=models.CharField(default='main/files/default_file.jpg', max_length=64),
        ),
    ]
